### ISSUE TITLE
there is no logs for release apk

### ISSUE THREAD

**Issue by fetchingly** [matomo-org/piwik-sdk-android#184]
the piwik service has no data  for the release APK,but debug APK has

**Comment by d4rken** [comment]
I don't know what you mean by that.

**Comment by d4rken** [comment]
We use `Timber` for logging, see:
https://github.com/JakeWharton/timber

Logging example:
https://github.com/piwik/piwik-sdk-android/blob/c081b54efb5048caa3636fe3a06c0726ff991a73/exampleapp/src/main/java/com/piwik/demo/DemoApp.java#L39

**Comment by PattaFeuFeu** [comment]
@d4rken By switching from `compile` to `implementation` for Timber—as opposed to using `api`—, Timber no longer gets included as a library that can be used by consumers of the SDK. So not even the DemoApp would work. Are you planning on changing that or should I import Timber in addition to the SDK in order to be able to use the `Timber.plant(new Timber.DebugTree());` statement?

**Comment by d4rken** [comment]
I'm not sure yet, I think a case could be made for both.

In any case it doesn't hurt if you manually include it for the time being.

**Comment by koteswaradk** [comment]
if any one implemented PIWIk for android app please help here. i am not able to implement as there is no any errors but not showing  tracking data in y portal
